version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"
      # networks:
      # - backend
  pgadmin:
    container_name: pgadmin_blog
    image: "dpage/pgadmin4:5.1"
    environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
        PGADMIN_DEFAULT_EMAIL: user@domain.local
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    # networks:
    #   - backend
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
      # networks:
      #   - backend
  frontend:
      container_name: bids-frontend
      image: bids-frontend
      ports:
        - "4200:80"

networks:
  backend:
    name: backend
    driver: bridge